# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  olympusapi:
    image: olympusapi
    build:
      context: .
      dockerfile: src/Olympus.Api/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5034:5034
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:c:\remote_debugger:rw
