# .github/ISSUE_TEMPLATE/feature_request.yml
name: Feature Request
description: Propose an enhancement for Olympus
title: "[Feature] <short summary>"
labels: ["enhancement", "needs triage"]
body:
  - type: markdown
    attributes:
      value: |
        Explain **why** this feature matters and how it fits Olympus's
        Clean Architecture, CQRS, and Event Sourcing approach.
  - type: input
    id: summary
    attributes:
      label: One-sentence summary
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Problem / motivation
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: High-level approach, API surface, UX notes
    validations:
      required: true
  - type: checkboxes
    id: scope
    attributes:
      label: Touches
      options:
        - label: Domain (Aggregates / Events)
        - label: Application (Commands / Queries / DTOs)
        - label: Api (Controllers / Endpoints)
        - label: Infrastructure (Marten / external adapters)
        - label: Bot / Discord
        - label: Frontend (Vue 3)
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      description: Bullet list, each item testable
      placeholder: |
        - [ ] command validated
        - [ ] event stored
